with open("csv") as file:
    lines= file.readlines();
    for line in lines:
        print(line)
        metrics = line.split(",")
        print("record type:",metrics[0])
        print("time: ",metrics[1])
        print("arl_id: ",metrics[2])
        print("fp_config_id: ",metrics[3] )
        print("traffic_type:(String) ",metrics[4])
        print("cdn_provider: ",metrics[5])
        print("cpcode: ",metrics[6])
        print("egress_hits: r13 ",metrics[7])
        print("egress_volume: r9  ",metrics[8])
        print("egress_volume_with_overhead:r9+r41 ",metrics[9])
        print("hits_2xx: ",metrics[10])
        print("hits_3xx: ",metrics[11])
        print("hits_4xx: ",metrics[12])
        print("hits_5xx: ",metrics[13])
        print("hits_xxx: ",metrics[14])
        print("hits_404: ",metrics[15])
        print("hits_429: ",metrics[16])
        print("egress_ttfb(r4+r5):",metrics[17])
        print("egress_tdt(r4+r5+r6): ",metrics[18])